In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st

 Temporal dynamics: Download the 2017 dataset on the data.gouv website and concatenate
it with 2018. Are there seasonal trends? Do accidents spike during specific holidays or specific
days of the week?

In [2]:
df18_car = pd.read_csv("acc-data/ACC-caracteristiques-2018.csv")
df18_lieux = pd.read_csv("acc-data/ACC-lieux-2018.csv")
df18_usag = pd.read_csv("acc-data/ACC-usagers-2018.csv")
df18_vehic = pd.read_csv("acc-data/ACC-vehicules-2018.csv")
#Individual df for 2018

/var/folders/xl/0wxp8zgx2wz1_sw2nyhksnr00000gn/T/ipykernel_9154/2945563687.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df18_lieux = pd.read_csv("acc-data/ACC-lieux-2018.csv")

In [3]:
df17_car = pd.read_csv("acc2017/caracteristiques-2017.csv",encoding='latin-1')
df17_lieux = pd.read_csv("acc2017/lieux-2017.csv",encoding='latin-1')
df17_usag = pd.read_csv("acc2017/usagers-2017.csv",encoding='latin-1')
df17_vehic = pd.read_csv("acc2017/vehicules-2017.csv",encoding='latin-1')
#individual df for 2017

/var/folders/xl/0wxp8zgx2wz1_sw2nyhksnr00000gn/T/ipykernel_9154/166248906.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df17_lieux = pd.read_csv("acc2017/lieux-2017.csv",encoding='latin-1')

In [4]:
df17_full = df17_car.merge(df17_lieux, on='Num_Acc', how='left') \
                    .merge(df17_vehic, on='Num_Acc', how='left') \
                    .merge(df17_usag, on=['Num_Acc', 'num_veh'], how='left')

df17_full
#Full 2017 Table

,Num_Acc,an,mois,jour,hrmn,lum,agg,int,atm,col,...,place,catu,grav,sexe,trajet,secu,locp,actp,etatp,an_nais
0,201700000001,17,1,11,1820,5,2,1,1.0,1.0,...,1.0,1.0,3.0,1.0,9.0,13.0,0.0,0.0,0.0,1968.0
1,201700000001,17,1,11,1820,5,2,1,1.0,1.0,...,2.0,2.0,3.0,2.0,9.0,11.0,0.0,0.0,0.0,1973.0
2,201700000001,17,1,11,1820,5,2,1,1.0,1.0,...,1.0,1.0,3.0,1.0,1.0,13.0,0.0,0.0,0.0,1967.0
3,201700000002,17,2,13,1630,1,2,3,1.0,3.0,...,1.0,1.0,1.0,1.0,0.0,11.0,0.0,0.0,0.0,1953.0
4,201700000002,17,2,13,1630,1,2,3,1.0,3.0,...,1.0,1.0,3.0,1.0,5.0,22.0,0.0,0.0,0.0,1960.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137903,201700060699,17,11,26,1745,2,2,1,1.0,3.0,...,1.0,1.0,1.0,2.0,9.0,11.0,0.0,0.0,0.0,1974.0
137904,201700060700,17,11,28,1405,1,2,1,1.0,3.0,...,1.0,1.0,1.0,2.0,9.0,11.0,0.0,0.0,0.0,1987.0
137905,201700060700,17,11,28,1405,1,2,1,1.0,3.0,...,1.0,1.0,4.0,1.0,9.0,21.0,0.0,0.0,0.0,1991.0
137906,201700060700,17,11,28,1405,1,2,1,1.0,3.0,...,2.0,2.0,4.0,2.0,9.0,21.0,0.0,0.0,0.0,1990.0
137907,201700060701,17,11,30,1939,3,2,1,1.0,6.0,...,1.0,1.0,4.0,1.0,1.0,21.0,0.0,0.0,0.0,1992.0

In [5]:
df18_full = df18_lieux.merge(df18_car, on='Num_Acc', how='left') \
                    .merge(df18_vehic, on='Num_Acc', how='left') \
                    .merge(df18_usag, on=['Num_Acc', 'num_veh'], how='left')

df18_full
#Full 2018 table

,Num_Acc,catr,voie,v1,v2,circ,nbv,pr,pr1,vosp,...,place,catu,grav,sexe,trajet,secu,locp,actp,etatp,an_nais
0,201800000001,3,41,NaN,C,2.0,2.0,NaN,NaN,0.0,...,1.0,1.0,3.0,1.0,0.0,11.0,0.0,0.0,0.0,1928.0
1,201800000001,3,41,NaN,C,2.0,2.0,NaN,NaN,0.0,...,1.0,1.0,1.0,1.0,5.0,11.0,0.0,0.0,0.0,1960.0
2,201800000002,4,41,NaN,D,2.0,2.0,NaN,NaN,0.0,...,1.0,1.0,1.0,1.0,0.0,11.0,0.0,0.0,0.0,1947.0
3,201800000002,4,41,NaN,D,2.0,2.0,NaN,NaN,0.0,...,NaN,3.0,4.0,1.0,0.0,2.0,2.0,3.0,1.0,1959.0
4,201800000003,3,39,NaN,D,2.0,2.0,NaN,NaN,0.0,...,1.0,1.0,3.0,1.0,5.0,21.0,0.0,0.0,0.0,1987.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131999,201800057781,2,1.0,NaN,NaN,2.0,2.0,0.0,0.0,0.0,...,NaN,3.0,4.0,1.0,9.0,3.0,4.0,3.0,1.0,1975.0
132000,201800057782,4,NaN,NaN,NaN,0.0,2.0,0.0,0.0,0.0,...,1.0,1.0,4.0,2.0,9.0,11.0,NaN,NaN,NaN,1993.0
132001,201800057782,4,NaN,NaN,NaN,0.0,2.0,0.0,0.0,0.0,...,1.0,1.0,4.0,1.0,9.0,21.0,NaN,NaN,NaN,1974.0
132002,201800057783,2,2.0,NaN,NaN,2.0,2.0,2.0,380.0,0.0,...,1.0,1.0,4.0,1.0,9.0,11.0,NaN,NaN,NaN,1973.0
132003,201800057783,2,2.0,NaN,NaN,2.0,2.0,2.0,380.0,0.0,...,1.0,1.0,4.0,2.0,9.0,11.0,NaN,NaN,NaN,1990.0

In [6]:
diff = len(df18_car['Num_Acc'])-len(df17_car['Num_Acc'])
diff
#Difference between amount of acc 2018 --> 2017

-2918

In [7]:

df_total = pd.concat([df17_full, df18_full], ignore_index=True)

print(f"total rows: {len(df_total)}")
print(df_total['an'].value_counts())

#Concatenated df (2017-2018)

total rows: 269912
an
17    137908
18    132004
Name: count, dtype: int64

In [8]:
# Filtra y muestra solo columnas con al menos un NaN
null = df_total.isnull().sum()
print(null[null > 0])

atm            35
col            21
adr          3276
gps         10494
lat         22512
long        22512
voie        68134
v1         268674
v2         257457
circ         1801
nbv          2201
pr         108476
pr1        109586
vosp         2605
prof         2060
plan         2978
lartpc     107706
larrout    106441
surf         2113
infra        9755
situ         9377
env1         9858
senc          267
obs           314
obsm          210
choc          210
manv          209
place       26484
catu         3722
grav         3722
sexe         3722
trajet       3847
secu        16801
locp        58419
actp        58411
etatp       58434
an_nais      3789
dtype: int64

In [9]:
df_total[df_total['atm']=='-1']

Empty DataFrame
Columns: [Num_Acc, an, mois, jour, hrmn, lum, agg, int, atm, col, com, adr, gps, lat, long, dep, catr, voie, v1, v2, circ, nbv, pr, pr1, vosp, prof, plan, lartpc, larrout, surf, infra, situ, env1, senc, catv, occutc, obs, obsm, choc, manv, num_veh, place, catu, grav, sexe, trajet, secu, locp, actp, etatp, an_nais]
Index: []

[0 rows x 51 columns]

In [11]:
df_total[df_total['dep'] ==690]

,Num_Acc,an,mois,jour,hrmn,lum,agg,int,atm,col,...,place,catu,grav,sexe,trajet,secu,locp,actp,etatp,an_nais
4074,201700001776,17,12,31,1730,5,2,1,1.0,6.0,...,1.0,1.0,1.0,1.0,0.0,21.0,0.0,0.0,0.0,1999.0
4075,201700001776,17,12,31,1730,5,2,1,1.0,6.0,...,NaN,3.0,4.0,2.0,5.0,91.0,3.0,6.0,1.0,1971.0
4076,201700001776,17,12,31,1730,5,2,1,1.0,6.0,...,1.0,1.0,1.0,1.0,0.0,13.0,0.0,0.0,0.0,1989.0
4077,201700001777,17,2,24,300,5,2,1,1.0,7.0,...,1.0,1.0,3.0,1.0,0.0,22.0,0.0,0.0,0.0,1981.0
4078,201700001778,17,5,14,2330,5,2,1,1.0,2.0,...,1.0,1.0,3.0,1.0,9.0,11.0,0.0,0.0,0.0,1994.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251495,201800049522,18,12,30,1125,1,1,1,1.0,3.0,...,1.0,1.0,2.0,1.0,5.0,11.0,NaN,NaN,NaN,1960.0
251496,201800049522,18,12,30,1125,1,1,1,1.0,3.0,...,2.0,2.0,1.0,2.0,5.0,11.0,NaN,NaN,NaN,1942.0
251497,201800049522,18,12,30,1125,1,1,1,1.0,3.0,...,3.0,2.0,4.0,2.0,5.0,11.0,NaN,NaN,NaN,2008.0
251498,201800049522,18,12,30,1125,1,1,1,1.0,3.0,...,4.0,2.0,1.0,2.0,5.0,11.0,NaN,NaN,NaN,1961.0
251499,201800049522,18,12,30,1125,1,1,1,1.0,3.0,...,1.0,1.0,1.0,1.0,5.0,11.0,NaN,NaN,NaN,1981.0

The weather factor: Does rain or fog actually increase the severity of accidents, or do people
simply drive slower? Cross-reference the weather conditions (atm) with the injury severity.

Demographics and machinery: Is there a correlation between the age of the driver and the
category of the vehicle? (e.g., Are young drivers more involved in motorcycle accidents? Do they
drive older vehicles?).

Infrastructure impact: Does the presence of a reserved lane (vosp) or the type of intersection
(int) drastically change the survival rate of cyclists and pedestrians?