In [4]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st

 Temporal dynamics: Download the 2017 dataset on the data.gouv website and concatenate
it with 2018. Are there seasonal trends? Do accidents spike during specific holidays or specific
days of the week?

In [13]:
df18_car = pd.read_csv("acc-data/ACC-caracteristiques-2018.csv")
df18_lieux = pd.read_csv("acc-data/ACC-lieux-2018.csv")
df18_usag = pd.read_csv("acc-data/ACC-usagers-2018.csv")
df18_vehic = pd.read_csv("acc-data/ACC-vehicules-2018.csv")

C:\Users\salva\AppData\Local\Temp\ipykernel_30424\3260820914.py:2: DtypeWarning: Columns (0: voie) have mixed types. Specify dtype option on import or set low_memory=False.
  df18_lieux = pd.read_csv("acc-data/ACC-lieux-2018.csv")

In [17]:
df17_car = pd.read_csv("acc2017/caracteristiques-2017.csv",encoding='latin-1')
df17_lieux = pd.read_csv("acc2017/lieux-2017.csv",encoding='latin-1')
df17_usag = pd.read_csv("acc2017/usagers-2017.csv",encoding='latin-1')
df17_vehic = pd.read_csv("acc2017/vehicules-2017.csv",encoding='latin-1')

C:\Users\salva\AppData\Local\Temp\ipykernel_30424\3185494215.py:2: DtypeWarning: Columns (0: voie) have mixed types. Specify dtype option on import or set low_memory=False.
  df17_lieux = pd.read_csv("acc2017/lieux-2017.csv",encoding='latin-1')

In [ ]:
pd.merge("df18_car","df18_lieux", "inner")

,Num_Acc,an,mois,jour,hrmn,lum,agg,int,atm,col,com,adr,gps,lat,long,dep
0,201800000001,18,1,24,1505,1,1,4,1.0,1.0,5,route des Ansereuilles,M,5055737.0,294992.0,590
1,201800000002,18,2,12,1015,1,2,7,7.0,7.0,11,Place du général de Gaul,M,5052936.0,293151.0,590
2,201800000003,18,3,4,1135,1,2,3,1.0,7.0,477,Rue nationale,M,5051243.0,291714.0,590
3,201800000004,18,5,5,1735,1,2,1,7.0,3.0,52,30 rue Jules Guesde,M,5051974.0,289123.0,590
4,201800000005,18,6,26,1605,1,2,1,1.0,3.0,477,72 rue Victor Hugo,M,5051607.0,290605.0,590

,Num_Acc,an,mois,jour,hrmn,lum,agg,int,atm,col,com,adr,gps,lat,long,dep
0,201700000001,17,1,11,1820,5,2,1,1.0,1.0,477,rue nationale,M,5051326.0,292191.0,590
1,201700000002,17,2,13,1630,1,2,3,1.0,3.0,5,5 rue sonneville,M,5053611.0,295314.0,590
2,201700000003,17,3,7,1150,1,2,9,1.0,5.0,52,rue Jules Guesde,M,5052174.0,288786.0,590
3,201700000004,17,4,22,1300,1,2,1,1.0,6.0,5,46 rue Sonneville,M,5053723.0,295700.0,590
4,201700000005,17,5,20,1230,1,2,1,1.0,2.0,11,Rue roger salengro,M,5052999.0,293798.0,590

The weather factor: Does rain or fog actually increase the severity of accidents, or do people
simply drive slower? Cross-reference the weather conditions (atm) with the injury severity.

Demographics and machinery: Is there a correlation between the age of the driver and the
category of the vehicle? (e.g., Are young drivers more involved in motorcycle accidents? Do they
drive older vehicles?).

Infrastructure impact: Does the presence of a reserved lane (vosp) or the type of intersection
(int) drastically change the survival rate of cyclists and pedestrians?